// Code generated by mockery v2.4.0-beta. DO NOT EDIT.

package mocks

import (
	model "github.com/lanemets/claim-funnel/model"
	mock "github.com/stretchr/testify/mock"
)

// BpmClaimClient is an autogenerated mock type for the BpmClaimClient type
type BpmClaimClient struct {
	mock.Mock
}

// StartProcessInstance provides a mock function with given fields: claimId
func (_m *BpmClaimClient) StartProcessInstance(claimId *model.ClaimId) (*model.ProcessDefinitionId, error) {
	ret := _m.Called(claimId)

	var r0 *model.ProcessDefinitionId
	if rf, ok := ret.Get(0).(func(*model.ClaimId) *model.ProcessDefinitionId); ok {
		r0 = rf(claimId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ProcessDefinitionId)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*model.ClaimId) error); ok {
		r1 = rf(claimId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
