// Code generated by mockery v2.4.0-beta. DO NOT EDIT.

package mocks

import (
	model "github.com/lanemets/claim-funnel/model"
	mock "github.com/stretchr/testify/mock"
)

// RpcClaim is an autogenerated mock type for the RpcClaim type
type RpcClaim struct {
	mock.Mock
}

// ConfirmClaim provides a mock function with given fields: claimId
func (_m *RpcClaim) ConfirmClaim(claimId *model.ClaimId) error {
	ret := _m.Called(claimId)

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.ClaimId) error); ok {
		r0 = rf(claimId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Create provides a mock function with given fields: claim, profile
func (_m *RpcClaim) Create(claim *model.Claim, profile *model.Profile) (*model.ClaimId, error) {
	ret := _m.Called(claim, profile)

	var r0 *model.ClaimId
	if rf, ok := ret.Get(0).(func(*model.Claim, *model.Profile) *model.ClaimId); ok {
		r0 = rf(claim, profile)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ClaimId)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*model.Claim, *model.Profile) error); ok {
		r1 = rf(claim, profile)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
