// Code generated by mockery v2.4.0-beta. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// RpcProfile is an autogenerated mock type for the RpcProfile type
type RpcProfile struct {
	mock.Mock
}
